/**
 * Flotiq User API
 * ## Getting started   This is your Flotiq User API that allows you to access your data through the Content API that you defined.   ### Access to data   There are several methods that you can use to access your data:  * Live API docs - available via [`Try it out`](https://apidoc.flotiq.com) button available next to each endpoint  * Copying example code on the right side of each endpoint  * By downloading the SDKs available in mulitple languages.  * By downloading the Postman collection and importing it into Postman.    Each of these methods is described in length in the [user documentation](https://flotiq.com/docs/).   ### Authorization   In order to make use of the provided documentation, example code, SDKs and so on - you will need to pull out your API key. We recommend that you start with the ReadOnly API Key which will allow you to make all the `GET` requests but will error-out when you try to modify content. Please remember to replace the key for `POST`, `PUT` and `DELETE` calls.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@flotiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbstractPropertiesConfig from './AbstractPropertiesConfig';

/**
 * The AbstractContentTypeMetaDefinition model module.
 * @module model/AbstractContentTypeMetaDefinition
 * @version 2.0.0
 */
class AbstractContentTypeMetaDefinition {
    /**
     * Constructs a new <code>AbstractContentTypeMetaDefinition</code>.
     * Meta definition to describe schema - add unique, fields labels
     * @alias module:model/AbstractContentTypeMetaDefinition
     * @param propertiesConfig {Object.<String, module:model/AbstractPropertiesConfig>} 
     * @param order {Array.<String>} 
     */
    constructor(propertiesConfig, order) { 
        
        AbstractContentTypeMetaDefinition.initialize(this, propertiesConfig, order);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, propertiesConfig, order) { 
        obj['propertiesConfig'] = propertiesConfig;
        obj['order'] = order;
    }

    /**
     * Constructs a <code>AbstractContentTypeMetaDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AbstractContentTypeMetaDefinition} obj Optional instance to populate.
     * @return {module:model/AbstractContentTypeMetaDefinition} The populated <code>AbstractContentTypeMetaDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AbstractContentTypeMetaDefinition();

            if (data.hasOwnProperty('propertiesConfig')) {
                obj['propertiesConfig'] = ApiClient.convertToType(data['propertiesConfig'], {'String': AbstractPropertiesConfig});
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/AbstractPropertiesConfig>} propertiesConfig
 */
AbstractContentTypeMetaDefinition.prototype['propertiesConfig'] = undefined;

/**
 * @member {Array.<String>} order
 */
AbstractContentTypeMetaDefinition.prototype['order'] = undefined;






export default AbstractContentTypeMetaDefinition;

