/**
 * Flotiq User API
 * ## Getting started   This is your Flotiq User API that allows you to access your data through the Content API that you defined.   ### Access to data   There are several methods that you can use to access your data:  * Live API docs - available via [`Try it out`](https://apidoc.flotiq.com) button available next to each endpoint  * Copying example code on the right side of each endpoint  * By downloading the SDKs available in mulitple languages.  * By downloading the Postman collection and importing it into Postman.    Each of these methods is described in length in the [user documentation](https://flotiq.com/docs/).   ### Authorization   In order to make use of the provided documentation, example code, SDKs and so on - you will need to pull out your API key. We recommend that you start with the ReadOnly API Key which will allow you to make all the `GET` requests but will error-out when you try to modify content. Please remember to replace the key for `POST`, `PUT` and `DELETE` calls.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@flotiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AbstractPropertiesConfigValidation model module.
 * @module model/AbstractPropertiesConfigValidation
 * @version 2.0.0
 */
class AbstractPropertiesConfigValidation {
    /**
     * Constructs a new <code>AbstractPropertiesConfigValidation</code>.
     * @alias module:model/AbstractPropertiesConfigValidation
     */
    constructor() { 
        
        AbstractPropertiesConfigValidation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AbstractPropertiesConfigValidation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AbstractPropertiesConfigValidation} obj Optional instance to populate.
     * @return {module:model/AbstractPropertiesConfigValidation} The populated <code>AbstractPropertiesConfigValidation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AbstractPropertiesConfigValidation();

            if (data.hasOwnProperty('relationMultiple')) {
                obj['relationMultiple'] = ApiClient.convertToType(data['relationMultiple'], 'Boolean');
            }
            if (data.hasOwnProperty('relationContenttype')) {
                obj['relationContenttype'] = ApiClient.convertToType(data['relationContenttype'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} relationMultiple
 */
AbstractPropertiesConfigValidation.prototype['relationMultiple'] = undefined;

/**
 * @member {String} relationContenttype
 */
AbstractPropertiesConfigValidation.prototype['relationContenttype'] = undefined;






export default AbstractPropertiesConfigValidation;

