/**
 * Flotiq User API
 * ## Getting started   This is your Flotiq User API that allows you to access your data through the Content API that you defined.   ### Access to data   There are several methods that you can use to access your data:  * Live API docs - available via [`Try it out`](https://apidoc.flotiq.com) button available next to each endpoint  * Copying example code on the right side of each endpoint  * By downloading the SDKs available in mulitple languages.  * By downloading the Postman collection and importing it into Postman.    Each of these methods is described in length in the [user documentation](https://flotiq.com/docs/).   ### Authorization   In order to make use of the provided documentation, example code, SDKs and so on - you will need to pull out your API key. We recommend that you start with the ReadOnly API Key which will allow you to make all the `GET` requests but will error-out when you try to modify content. Please remember to replace the key for `POST`, `PUT` and `DELETE` calls.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@flotiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AbstractContentTypeSchemaDefinitionInternal model module.
 * @module model/AbstractContentTypeSchemaDefinitionInternal
 * @version 2.0.0
 */
class AbstractContentTypeSchemaDefinitionInternal {
    /**
     * Constructs a new <code>AbstractContentTypeSchemaDefinitionInternal</code>.
     * @alias module:model/AbstractContentTypeSchemaDefinitionInternal
     * @param contentType {String} 
     * @param createdAt {String} 
     * @param updatedAt {String} 
     * @param deletedAt {String} 
     */
    constructor(contentType, createdAt, updatedAt, deletedAt) { 
        
        AbstractContentTypeSchemaDefinitionInternal.initialize(this, contentType, createdAt, updatedAt, deletedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contentType, createdAt, updatedAt, deletedAt) { 
        obj['contentType'] = contentType;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
        obj['deletedAt'] = deletedAt;
    }

    /**
     * Constructs a <code>AbstractContentTypeSchemaDefinitionInternal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AbstractContentTypeSchemaDefinitionInternal} obj Optional instance to populate.
     * @return {module:model/AbstractContentTypeSchemaDefinitionInternal} The populated <code>AbstractContentTypeSchemaDefinitionInternal</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AbstractContentTypeSchemaDefinitionInternal();

            if (data.hasOwnProperty('contentType')) {
                obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('deletedAt')) {
                obj['deletedAt'] = ApiClient.convertToType(data['deletedAt'], 'String');
            }
            if (data.hasOwnProperty('_workflow')) {
                obj['_workflow'] = ApiClient.convertToType(data['_workflow'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} contentType
 */
AbstractContentTypeSchemaDefinitionInternal.prototype['contentType'] = undefined;

/**
 * @member {String} createdAt
 */
AbstractContentTypeSchemaDefinitionInternal.prototype['createdAt'] = undefined;

/**
 * @member {String} updatedAt
 */
AbstractContentTypeSchemaDefinitionInternal.prototype['updatedAt'] = undefined;

/**
 * @member {String} deletedAt
 */
AbstractContentTypeSchemaDefinitionInternal.prototype['deletedAt'] = undefined;

/**
 * @member {Object} _workflow
 */
AbstractContentTypeSchemaDefinitionInternal.prototype['_workflow'] = undefined;






export default AbstractContentTypeSchemaDefinitionInternal;

