/**
 * Flotiq User API
 * ## Getting started   This is your Flotiq User API that allows you to access your data through the Content API that you defined.   ### Access to data   There are several methods that you can use to access your data:  * Live API docs - available via [`Try it out`](https://apidoc.flotiq.com) button available next to each endpoint  * Copying example code on the right side of each endpoint  * By downloading the SDKs available in mulitple languages.  * By downloading the Postman collection and importing it into Postman.    Each of these methods is described in length in the [user documentation](https://flotiq.com/docs/).   ### Authorization   In order to make use of the provided documentation, example code, SDKs and so on - you will need to pull out your API key. We recommend that you start with the ReadOnly API Key which will allow you to make all the `GET` requests but will error-out when you try to modify content. Please remember to replace the key for `POST`, `PUT` and `DELETE` calls.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@flotiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BatchResponseErrors1 from './BatchResponseErrors1';

/**
 * The BatchResponse model module.
 * @module model/BatchResponse
 * @version 2.0.0
 */
class BatchResponse {
    /**
     * Constructs a new <code>BatchResponse</code>.
     * @alias module:model/BatchResponse
     */
    constructor() { 
        
        BatchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BatchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchResponse} obj Optional instance to populate.
     * @return {module:model/BatchResponse} The populated <code>BatchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchResponse();

            if (data.hasOwnProperty('batch_total_count')) {
                obj['batch_total_count'] = ApiClient.convertToType(data['batch_total_count'], 'Number');
            }
            if (data.hasOwnProperty('batch_success_count')) {
                obj['batch_success_count'] = ApiClient.convertToType(data['batch_success_count'], 'Number');
            }
            if (data.hasOwnProperty('batch_error_count')) {
                obj['batch_error_count'] = ApiClient.convertToType(data['batch_error_count'], 'Number');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [BatchResponseErrors1]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} batch_total_count
 */
BatchResponse.prototype['batch_total_count'] = undefined;

/**
 * @member {Number} batch_success_count
 */
BatchResponse.prototype['batch_success_count'] = undefined;

/**
 * @member {Number} batch_error_count
 */
BatchResponse.prototype['batch_error_count'] = undefined;

/**
 * @member {Array.<module:model/BatchResponseErrors1>} errors
 */
BatchResponse.prototype['errors'] = undefined;






export default BatchResponse;

