/**
 * Flotiq User API
 * ## Getting started   This is your Flotiq User API that allows you to access your data through the Content API that you defined.   ### Access to data   There are several methods that you can use to access your data:  * Live API docs - available via [`Try it out`](https://apidoc.flotiq.com) button available next to each endpoint  * Copying example code on the right side of each endpoint  * By downloading the SDKs available in mulitple languages.  * By downloading the Postman collection and importing it into Postman.    Each of these methods is described in length in the [user documentation](https://flotiq.com/docs/).   ### Authorization   In order to make use of the provided documentation, example code, SDKs and so on - you will need to pull out your API key. We recommend that you start with the ReadOnly API Key which will allow you to make all the `GET` requests but will error-out when you try to modify content. Please remember to replace the key for `POST`, `PUT` and `DELETE` calls.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@flotiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbstractContentTypeSchemaDefinition from './AbstractContentTypeSchemaDefinition';
import AbstractContentTypeSchemaDefinitionInternal from './AbstractContentTypeSchemaDefinitionInternal';
import DataSource from './DataSource';
import QuestionAllOf from './QuestionAllOf';

/**
 * The Question model module.
 * @module model/Question
 * @version 2.0.0
 */
class Question {
    /**
     * Constructs a new <code>Question</code>.
     * @alias module:model/Question
     * @implements module:model/AbstractContentTypeSchemaDefinition
     * @implements module:model/QuestionAllOf
     * @param id {String} 
     * @param text {String} 
     * @param type {String} 
     * @param answers {String} 
     */
    constructor(id, text, type, answers) { 
        AbstractContentTypeSchemaDefinition.initialize(this, id);QuestionAllOf.initialize(this);
        Question.initialize(this, id, text, type, answers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, text, type, answers) { 
        obj['id'] = id;
        obj['text'] = text;
        obj['type'] = type;
        obj['answers'] = answers;
    }

    /**
     * Constructs a <code>Question</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Question} obj Optional instance to populate.
     * @return {module:model/Question} The populated <code>Question</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Question();
            AbstractContentTypeSchemaDefinition.constructFromObject(data, obj);
            QuestionAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('internal')) {
                obj['internal'] = AbstractContentTypeSchemaDefinitionInternal.constructFromObject(data['internal']);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('nextQuestions')) {
                obj['nextQuestions'] = ApiClient.convertToType(data['nextQuestions'], [DataSource]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Question.prototype['id'] = undefined;

/**
 * @member {module:model/AbstractContentTypeSchemaDefinitionInternal} internal
 */
Question.prototype['internal'] = undefined;

/**
 * @member {String} text
 */
Question.prototype['text'] = undefined;

/**
 * @member {String} type
 * @default 'question'
 */
Question.prototype['type'] = 'question';

/**
 * @member {String} answers
 */
Question.prototype['answers'] = undefined;

/**
 * @member {String} description
 */
Question.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/DataSource>} nextQuestions
 */
Question.prototype['nextQuestions'] = undefined;


// Implement AbstractContentTypeSchemaDefinition interface:
/**
 * @member {String} id
 */
AbstractContentTypeSchemaDefinition.prototype['id'] = undefined;
/**
 * @member {module:model/AbstractContentTypeSchemaDefinitionInternal} internal
 */
AbstractContentTypeSchemaDefinition.prototype['internal'] = undefined;
// Implement QuestionAllOf interface:
/**
 * @member {String} text
 */
QuestionAllOf.prototype['text'] = undefined;
/**
 * @member {String} type
 * @default 'question'
 */
QuestionAllOf.prototype['type'] = 'question';
/**
 * @member {String} answers
 */
QuestionAllOf.prototype['answers'] = undefined;
/**
 * @member {String} description
 */
QuestionAllOf.prototype['description'] = undefined;
/**
 * @member {Array.<module:model/DataSource>} nextQuestions
 */
QuestionAllOf.prototype['nextQuestions'] = undefined;




export default Question;

